### ISSUE TITLE
Content design for "what's new" page

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template#216]
Review and provide suggested edits for the Update page updated content: (in beta staging)
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/update.html

Original page to compare:
https://beta.template.webstandards.ca.gov/update.html

**Comment by ashleydraper** [comment]
[What's new content staging document](https://docs.google.com/document/d/15_Qr6ahAbD_L4S-pnl8707AWRRRsS8RZI3EAeFKGRbM/edit)

**Comment by ashleydraper** [comment]
Posted question to engineering team in [slack](https://cadotgov.slack.com/archives/C01VC9U82H1/p1655339502232099) about how best to communicate steps that speak to comparing ones current version of the state template to the latest version. 

Recommendation to have clearer upgrade instructions in the changelog or release **notes.** Could follow the [Spectrum Design System](https://spectrum.adobe.com/page/whats-new/) model.

**Comment by kkoryaka** [comment]
@ashleydraper please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/update.html

**Comment by ashleydraper** [comment]
Sending this issue back to @Courtney-Chittock to mock up design for the marketing section. This section will feel similar to the DWSN presentation on 7/21/2022.

**Comment by yesenia-gtz** [comment]
@ashleydraper @extinah can we meet as a team to help prioritize content needs for this? perhaps an outline of items to share on page to get this moving. 

Plan for:
- Beta "Whats New"
- Evergreen "Whats new" for production release

**Comment by Courtney-Chittock** [comment]
@yesenia-gtz @ashleydraper @sharon-rabang [here is the Figma page](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=868%3A4289) where I started to design the "What's new" section. It will be on the "Template updates" page, with a link from the homepage.

**Comment by extinah** [comment]
@yesenia-gtz  be sure to add yourself as an assignee and remove @ashleydraper. She can provide feedback if she wants to (or not) later in the process.

**Comment by Courtney-Chittock** [comment]
Just to document, the decision is to have "What's new" as a separate page now, with links to it from the homepage and "Template updates" page. I am working on a content draft for this page and will let @yesenia-gtz  and @sharon-rabang make it look purty. :)

**Comment by kkoryaka** [comment]
@kkoryaka meet with @sharon-rabang and talk about implications of the updated design and navigation for this page.

**Comment by ashleydraper** [comment]
**[What's new](https://docs.google.com/document/d/1Rl-IssNrdLauJfyBEBwbQnM-77YLIEf7MMYFsY3QgJo/edit#)** content is now ready for review. Assigning to Art and Christina.

**Comment by ashleydraper** [comment]
@sharon-rabang Content is approved and final! I've already updated the [**Figma**](**url**) board with the final content, the only design need is on the feedback line at the bottom of the page.

**Comment by ashleydraper** [comment]
Per discussion on 10/12/22, we will not publish a page level feedback form. This issue is ready for dev.

**Comment by kkoryaka** [comment]
@ashleydraper this is now ready for review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/whats-new.html

**Comment by ashleydraper** [comment]
Looks good. Ready to close.
