### ISSUE TITLE
Redesign navigation samples landing page

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template#293]
1. Add schematic images (or actual screenshots) under each navigation option to show users the basic idea of those navigation options. 
2. Update side navigation on each navigation sample page, so it is showing only navigation links. 
3. Add text on each nav sample page that letting users know that that particular navigation sample page is using actually using that particular navigation option.

**Comment by Courtney-Chittock** [comment]
Here's the [current design](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=616%3A3992). All the Structure pages are on the project Figma board now.

**Comment by kkoryaka** [comment]
this one is already tracked in #306 Closing this one.
