### ISSUE TITLE
Licensing and use?

### ISSUE THREAD

**Issue by rasmi** [Office-of-Digital-Services/California-State-Web-Template#298]
Hi, is there anywhere that the project documents terms around licensing or use of code or other resources? I would like to include some of the SVG icons in a project and could not find a clear answer in the repository. Thanks!

**Comment by kkoryaka** [comment]
Makes total sense, we will add general public license to this project in our next release.

**Comment by rasmi** [comment]
Thank you! I did eventually see on the website (under the [Ownership section here](https://template.webstandards.ca.gov/use.html)) that the resources are available in the public domain. USWDS licenses their code specifically as such [in their repo](https://github.com/uswds/uswds/blob/d3f7adff47b97c11a7232f818d2e684136defef3/LICENSE.md#the-rest-of-this-project-is-in-the-worldwide-public-domain), which would be helpful here too. Thanks for including it in the next release!

**Comment by yesenia-gtz** [comment]
@kkoryaka Has this been resolved?

**Comment by kkoryaka** [comment]
@yesenia-gtz general public license is added to the beta v6 release. I am closing this issue.
