### ISSUE TITLE
Component content audit [accordion]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#311]
Submitted the following email-

To: Koryaka, Konstantin@CIO <Konstantin.Koryaka@state.ca.gov>; Wasylkiw, Blaine@CIO <blaine.wasylkiw@state.ca.gov>
Cc: Khomishen, Artem@CIO <Artem.Khomishen@state.ca.gov>; Koryaka, Konstantin@CIO <Konstantin.Koryaka@state.ca.gov>; Chittock, Courtney@CIO <courtney.chittock@state.ca.gov>; Gutierrez, Yesenia@CIO <yesenia.gutierrez@state.ca.gov>
Date: 5/19/22
Subject: State Template - Accordion Component

The accordion component is now ready for review/ approval. 

Courtney and I have ironed out the content and design for this component. This will be the only one mocked up in Figma. 

Each subsequent component will follow this template, but will be in Google doc form for the approval process.
•	Use the attached PDF to view the full mockup of the accordion component. This view is the look and feel of the redesign.
•	Use the [Accordion component google doc](https://docs.google.com/document/d/11GtQjhuwab5f0Xw-t1ksxuKhaKMzjhXBtEuNYbQ3yrk/edit) for copy editing. Please use track changes.
Please submit any feedback or edits on or before COB **Friday, May 27th**.

Attachments: [Accordion-Component-State-Template-V6-Release.pdf](https://github.com/Office-of-Digital-Innovation/California-State-Web-Template/files/8789386/Accordion-Component-State-Template-V6-Release.pdf)

**Comment by ashleydraper** [comment]
The [accordion component](https://docs.google.com/document/d/11GtQjhuwab5f0Xw-t1ksxuKhaKMzjhXBtEuNYbQ3yrk/edit#heading=h.xv7rpjtvd3w5) has been reviewed/approved and is current in Figma. Assigning to @Courtney-Chittock for any needed design updates before sharing with dev.

**Comment by Courtney-Chittock** [comment]
@ashleydraper I made a few small recommendations on the [source doc](https://docs.google.com/document/d/11GtQjhuwab5f0Xw-t1ksxuKhaKMzjhXBtEuNYbQ3yrk/edit#). Once we finalize that text and true up the Figma board this is good for dev.

**Comment by Courtney-Chittock** [comment]
@kkoryaka I also did my UX review. See #30-35 on the [project tracker](https://docs.google.com/spreadsheets/d/11j0r3flPCG5wvpa5flClG8x5-e0ZxROl-HQoaTkSsNM/edit#gid=156389168).

![image](https://user-images.githubusercontent.com/99773875/179324257-bf109956-9f42-40a6-802c-0a6f77cdbcdc.png)

**Comment by Courtney-Chittock** [comment]
PS: sorry that I duplicated Ashley's comment above on one of my findings.

**Comment by kkoryaka** [comment]
@ashleydraper @Courtney-Chittock please review it again

**Comment by ashleydraper** [comment]
@kkoryaka Completed my review.

![image](https://user-images.githubusercontent.com/62437425/192043171-6d98d004-bd04-4b45-85ac-af8abaf054a4.png)



![image](https://user-images.githubusercontent.com/62437425/192043950-762a3370-c763-47ae-bd72-0af9680e5631.png)



![image](https://user-images.githubusercontent.com/62437425/192043960-184c10ce-c066-4dd1-ac86-123e64d5468f.png)

**Comment by kkoryaka** [comment]
@ashleydraper I added periods. However, I don't see any difference between my accordion tabs content and word doc's content. Please review it again and if I missed something reach me out in teams.

**Comment by ashleydraper** [comment]
Looks good, moving to close.
