### ISSUE TITLE
Component content audit [alert banner]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#312]
<<This email was shared seeking feedback/ approval>>

To: Kumpulainien, Koji@CIO <koji.kumpulainien@state.ca.gov>; Khomishen, Artem@CIO <Artem.Khomishen@state.ca.gov>
Cc: Wasylkiw, Blaine@CIO <blaine.wasylkiw@state.ca.gov>; Gutierrez, Yesenia@CIO <yesenia.gutierrez@state.ca.gov>; Chittock, Courtney@CIO <courtney.chittock@state.ca.gov>; Koryaka, Konstantin@CIO <Konstantin.Koryaka@state.ca.gov>
Date: 5/23/22

The alert banner component is now ready for review/ approval. 

Note, this component is referred to as the “page alert” in the design system. I did some [quick desk research](https://docs.google.com/document/d/1eazq2mj8mN93knn59O23nuitDduSCsVpmsLxnD2y5T8/edit#heading=h.2udjis843acb) comparing 4 other design systems and landed on an alert banner.

Use the [alert banner component google doc](https://docs.google.com/document/d/1eazq2mj8mN93knn59O23nuitDduSCsVpmsLxnD2y5T8/edit#heading=h.l80mj49mpel5) for copy editing. Please use track changes.

Please submit any feedback or edits on or before COB **Friday, May 27th**.

**Comment by ashleydraper** [comment]
Content is ready for dev. Follow the **[accordion design](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=203%3A2786)** in Figma for layout. See Courtney for design of example section.

Cc: @Courtney-Chittock

**Comment by kkoryaka** [comment]
@ashleydraper this is now updated in staging. Please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/alert-banner.html

**Comment by ashleydraper** [comment]
@kkoryaka Please review these edits-
![image](https://user-images.githubusercontent.com/62437425/176767864-2f2d9296-b579-41a9-8e47-f67a8ca6da70.png)

**Comment by ashleydraper** [comment]
@kkoryaka Please review these edits
![image](https://user-images.githubusercontent.com/62437425/176772419-8f6de8bc-c736-4104-b287-632237d26edf.png)

**Comment by kkoryaka** [comment]
@ashleydraper this is now updated. Please review once more.

**Comment by ashleydraper** [comment]
@kkoryaka Looking good. Just one more edit and we're good here.
![image](https://user-images.githubusercontent.com/62437425/179117617-873daddd-4b73-4696-b1a4-432c729fea37.png)

**Comment by ashleydraper** [comment]
@kkoryaka We removed "banner" from the title of this component on July 14, but I don't see that mocked up. Reassigning to you.

![image](https://user-images.githubusercontent.com/62437425/179791500-1bd8635f-4912-4bf2-9a94-bd909700ef3b.png)

**Comment by ashleydraper** [comment]
@kkoryaka A substantial amount of content does not match the [google staging doc](https://docs.google.com/document/d/1eazq2mj8mN93knn59O23nuitDduSCsVpmsLxnD2y5T8/edit#). Can you re-copy and paste?

**Comment by kkoryaka** [comment]
@ashleydraper I have updated the content. Please review again: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/alert.html

**Comment by ashleydraper** [comment]
Looks good, moving to close.
