### ISSUE TITLE
New Feature: Copy code button

### ISSUE THREAD

**Issue by Courtney-Chittock** [Office-of-Digital-Services/California-State-Web-Template#314]
Add "copy code" button so users can easily copy code with one click.
[Feature mockup](https://www.figma.com/file/Vt2Y8p4mXyzDNqT69KIb6H/Courtney's-Sandbox?node-id=340%3A2773)

Main audience: web developers
Location: Below all source code containers. [See Figma mockup](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=203%3A2823).

**Comment by kkoryaka** [comment]
@Greg-Watanabe you can work on this button. use this new icon with it:
![Screen Shot 2022-09-28 at 10 56 26 AM](https://user-images.githubusercontent.com/31669748/192854716-4f1165eb-4ade-48c4-9dec-34ccc0e74fc9.png)

**Comment by Courtney-Chittock** [comment]
@Greg-Watanabe my friend at the EDD implemented this functionality. Different code base, so maybe not helpful, but I am attaching his development notes just in case they have value to you.

[Implementing copy and paste functions.docx](https://github.com/Office-of-Digital-Services/California-State-Web-Template/files/9667812/Implementing.copy.and.paste.functions.docx)

**Comment by Greg-Watanabe** [comment]
#527

**Comment by kkoryaka** [comment]
@yesenia-gtz This one is ready for review. Click on Source code tab
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/lists.html

**Comment by ashleydraper** [comment]
This looks good. Ready to close.
