### ISSUE TITLE
Component content audit [breadcrumb]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#323]
<<This email was shared seeking feedback/ approval>>

To: Kumpulainien, Koji@CIO koji.kumpulainien@state.ca.gov; Khomishen, Artem@CIO Artem.Khomishen@state.ca.gov
Cc: Wasylkiw, Blaine@CIO blaine.wasylkiw@state.ca.gov; Gutierrez, Yesenia@CIO yesenia.gutierrez@state.ca.gov; Chittock, Courtney@CIO courtney.chittock@state.ca.gov; Koryaka, Konstantin@CIO Konstantin.Koryaka@state.ca.gov
Date: 5/24/22

The breadcrumb component is now ready for review/ approval.
Use the **[breadcrumb component google doc](https://docs.google.com/document/d/1he_wH2H_59JmuOXfTJuXDANV5bofqRmFFCl5O6UpqxM/edit#)** for copy editing. Please use track changes.
Submit any feedback or edits on or before COB **Friday, June 3rd**.

**Comment by ashleydraper** [comment]
[Breadcrumb content](https://docs.google.com/document/d/1he_wH2H_59JmuOXfTJuXDANV5bofqRmFFCl5O6UpqxM/edit#) is ready for dev. Follow the [accordion design](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=203%3A2786) in Figma for layout. See Courtney for design of example section.

Cc: @Courtney-Chittock

**Comment by ashleydraper** [comment]
@kkoryaka Looks great! Just a couple things to note.

1. The "demo and source code" H2 heading should be updated to "sample"
![image](https://user-images.githubusercontent.com/62437425/176759185-f9a0aa66-1cf6-4db9-9d05-0999326b5a5b.png)

2. Please add a break (make new paragraph) in the "how not to use it" section.
![image](https://user-images.githubusercontent.com/62437425/176760066-409a5b73-0f83-4f0b-932b-4094d6625201.png)

**Comment by kkoryaka** [comment]
@ashleydraper made those edits. Please review again.

**Comment by ashleydraper** [comment]
@kkoryaka This looks excellent. Great work. I will close the issue.

Cc: @Courtney-Chittock @extinah @artuoma

**Comment by ashleydraper** [comment]
Whoops, reopening and moving to merge to beta

**Comment by Courtney-Chittock** [comment]
@kkoryaka I completed my UX review. See numbers 36-38 on the [project tracker](https://docs.google.com/spreadsheets/d/11j0r3flPCG5wvpa5flClG8x5-e0ZxROl-HQoaTkSsNM/edit#gid=156389168).

![image](https://user-images.githubusercontent.com/99773875/179820479-e9c46a78-f154-40b1-9c2b-5e05becb1442.png)

**Comment by kkoryaka** [comment]
@Courtney-Chittock please review. As far as changing the URL i put not feasible status for now. We will meet with Art and discuss it.

**Comment by yesenia-gtz** [comment]
@artuoma reassigned to you for review. are we OK with keeping as and moving into dev?

**Comment by ashleydraper** [comment]
@kkoryaka Can you re-share the link where this is staged? I can't access it for some reason.

**Comment by kkoryaka** [comment]
@ashleydraper here you go https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/breadcrumb.html

**Comment by ashleydraper** [comment]
@yesenia-gtz This component has already gone to dev. Content looks great, this issue is now ready to move to QA.

**Comment by ashleydraper** [comment]
@kkoryaka Do the slugs look like this because we're in staging, or what's going on with these?

https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/alert-banner.html
