### ISSUE TITLE
Component content audit [countdown-timer]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#326]
Draft in progress for the **[countdown component](https://docs.google.com/document/d/1Vas40gy7wU29TzJ5Jxc7_NN-aCMJEIIEupck-gtPak0/edit#heading=h.xv7rpjtvd3w5)**.

**Comment by ashleydraper** [comment]
@extinah @artuoma This one is ready for content review.

[countdown component](https://docs.google.com/document/d/1Vas40gy7wU29TzJ5Jxc7_NN-aCMJEIIEupck-gtPak0/edit#heading=h.xv7rpjtvd3w5)

**Comment by ashleydraper** [comment]
@Courtney-Chittock This is ready for design, content was reviewed and approved by Art.

**Comment by kkoryaka** [comment]
@ashleydraper this one is ready for review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/countdown.html

**Comment by ashleydraper** [comment]
@kkoryaka 

I've decided to leave this title as is and will work on a new title for the number counter component. 

Here's what I found in my review.

![image](https://user-images.githubusercontent.com/62437425/183116369-a68d200a-02ef-42d8-bf37-3847c931feea.png)

![image](https://user-images.githubusercontent.com/62437425/183116767-00e56dad-edd3-4b6c-8da9-be96c90a1f52.png)

**Comment by ashleydraper** [comment]
![image](https://user-images.githubusercontent.com/62437425/183116767-00e56dad-edd3-4b6c-8da9-be96c90a1f52.png)

**Comment by kkoryaka** [comment]
@ashleydraper please review it again.

**Comment by yesenia-gtz** [comment]
@ashleydraper ready for review

**Comment by ashleydraper** [comment]
[Staging link](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/countdown.html)

**Comment by ashleydraper** [comment]
@kkoryaka The staged page does not match the google staging doc. See comments.

![image](https://user-images.githubusercontent.com/62437425/192038254-f2cc7d97-b0e3-4ad1-b3b9-6a5921325e13.png)

**Comment by kkoryaka** [comment]
@ashleydraper we have two versions (dark and light), I't looks like you want only dark (primary) version. But we don't remove existing versions and code from the template. 

We need to discuss it  with @extinah and @artuoma or @yesenia-gtz

**Comment by kkoryaka** [comment]
@kkoryaka show two in the example tab

**Comment by kkoryaka** [comment]
@ashleydraper page is now updated. Please review it again

**Comment by ashleydraper** [comment]
![image](https://user-images.githubusercontent.com/62437425/194685539-1dc1e31f-821b-4cc0-aaab-1cdafa64f938.png)

**Comment by kkoryaka** [comment]
@ashleydraper this one is fixed

**Comment by ashleydraper** [comment]
@kkoryaka You have to provide the new staging link.

**Comment by ashleydraper** [comment]
Looks good. Ready to close.
