### ISSUE TITLE
Component content audit [horizontal rule]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#409]
Drafting content for the [horizontal rule](https://docs.google.com/document/d/16Bz8pAphFQIsWxk2DrkHVRnCcrSmgusX8go-TJqSzQA/edit#) component in this google staging doc.

**Comment by extinah** [comment]
HI there - my review is done. Some comments are included.

**Comment by ashleydraper** [comment]
@artuoma I've taken another content pass and included feedback from the team. Ready for your review.

[horizontal rule](https://docs.google.com/document/d/16Bz8pAphFQIsWxk2DrkHVRnCcrSmgusX8go-TJqSzQA/edit#)

**Comment by ashleydraper** [comment]
![image](https://user-images.githubusercontent.com/62437425/195432129-4f94d7d8-4043-4636-9b3e-2008ba5bc68d.png)

**Comment by ashleydraper** [comment]
Looks good. Ready to close.
