### ISSUE TITLE
Component content audit [Lists]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#410]
After a lengthy team discussion, we will merge the **list** component with the **news list** pattern into one content pattern. This merge will also absorb the **step list** component.

Together, the variants for the **lists** pattern will include
- Standard lists
> ordered
> un-ordered
- Multi-line lists
- News Lists

For details on this discussion, see State Template standup thread beginning at 3:58PM on 7/19/22.

**Comment by ashleydraper** [comment]
Draft content can be found in this [lists pattern google staging doc](https://docs.google.com/document/d/1dXEkoN760Q1J3MC1WVE3R5AtjHFIum84WoXsX824pzY/edit#heading=h.xv7rpjtvd3w5).

**Comment by ashleydraper** [comment]
This draft is ready for Art/Christina review.

**Comment by extinah** [comment]
@ashleydraper  we may need a small meeting on this one. 
@artuoma I did my review - your input would be nice before we meet. thanks!

**Comment by ashleydraper** [comment]
List should move to component. Separate the "news list" as its own pattern.

**Comment by kkoryaka** [comment]
@kkoryaka "step list" is merged with "progress tacker" pattern

**Comment by ashleydraper** [comment]
@kkoryaka This component is now ready for dev. If it's already staged, will you please paste the link?

**Comment by kkoryaka** [comment]
@ashleydraper this one is ready for review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/lists.html

**Comment by ashleydraper** [comment]
Looks good. Ready to close.
