### ISSUE TITLE
Component content audit [table]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#412]

**Comment by ashleydraper** [comment]
@artuoma 
The **[table component](https://docs.google.com/document/d/1wti96QD3bOLNDnVat3PufHeComN2FF7U76S6VWTKG0g/edit#)** is ready for review.

**Comment by extinah** [comment]
Review - added in suggested content.
@artuoma  ready for your review.

**Comment by ashleydraper** [comment]
@kkoryaka  How about just these:

Basic
![image](https://user-images.githubusercontent.com/62437425/195192159-84082263-35e8-453e-a32b-8b59e81244f9.png)

Shaded
![image](https://user-images.githubusercontent.com/62437425/195191907-56acfac3-755f-42d6-bec0-a1a5f7e6fe69.png)

**Comment by ashleydraper** [comment]
Looks good. Ready to close.
