### ISSUE TITLE
Component content audit [social media icons]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#414]

**Comment by ashleydraper** [comment]
The **[social media icon](https://docs.google.com/document/d/1WQZ71PA9ZIit5Y48mLNxdgHChrq3qdDN6ZJM57T1VxY/edit#heading=h.wmymts22289n) **component is ready for review.

**Comment by kkoryaka** [comment]
@ashleydraper this one is updated please review https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/social-media-icons.html

**Comment by ashleydraper** [comment]
![image](https://user-images.githubusercontent.com/62437425/194684973-bb8396fb-13c1-426a-b0b3-ec6aeee1f02c.png)

**Comment by kkoryaka** [comment]
@ashleydraper this one is now fixed

**Comment by ashleydraper** [comment]
@kkoryaka I just tagged you in the Figma doc where the social media icons are located. I believe these all exist, can you add them to our sample section. 

Once that is done, this issue can close.

![image](https://user-images.githubusercontent.com/62437425/195141418-3bf55687-f592-4152-b2fa-ea5a71adb3d8.png)
