### ISSUE TITLE
Component content audit [progress bar]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#415]

**Comment by ashleydraper** [comment]
@artuoma The [progress bar](https://docs.google.com/document/d/1mYrR0uhLpz9aPQrDp3obxXEzv11z2eOS1qKgSkZhDR0/edit#) component is ready for your review.

**Comment by extinah** [comment]
Decision: This is a content pattern. We moved step list here, too.

**Comment by kkoryaka** [comment]
this one is the component and should be on the component list.

**Comment by ashleydraper** [comment]
Looks good. Ready to close.
