### ISSUE TITLE
Component content audit [number counter]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#416]

**Comment by ashleydraper** [comment]
@artuoma The [rolling number counter](https://docs.google.com/document/d/1EIC1aNhbuYCmYWxdLVlVC_efDQs8pWVwtzzjxEct1nw/edit#heading=h.2cyxougan0v) component is ready for review. Take a look.

**Comment by extinah** [comment]
@ashleydraper my review is completed. @artuoma reminder to review :) Just agreed with Courtney's comments.

**Comment by extinah** [comment]
@ashleydraper  review is done by me and Art.

**Comment by kkoryaka** [comment]
@ashleydraper this is now updated https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/number-counter.html

**Comment by ashleydraper** [comment]
![image](https://user-images.githubusercontent.com/62437425/194910729-2514d742-8bad-426b-8f80-dee9cc6cfa6f.png)

**Comment by kkoryaka** [comment]
@sharon-rabang said she will work on subtile and provides me the concrete styles.

**Comment by kkoryaka** [comment]
@ashleydraper subtitle is now updated (based on @sharon-rabang recommendations) Please review

**Comment by ashleydraper** [comment]
Looks good. Ready to close.

**Comment by sharon-rabang** [comment]
Here's the [Typography: Subtitle](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=57%3A5135) prototype in Figma, for reference.

**Comment by ashleydraper** [comment]
So sorry for all the back and forth on this one. I'm just seeing Sharon's mockup in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=57%3A5135). The heading should look like this.

![image](https://user-images.githubusercontent.com/62437425/195203378-ff5bb6a8-ec94-4dfe-95bd-032edc8a71b8.png)

**Comment by sharon-rabang** [comment]
@ashleydraper FYI - The H1 color will get updated when we apply the v6 website colors in Dev. I'm still working on colors in Figma. :)

**Comment by ashleydraper** [comment]
Sounds good. Re-closing this issue.
