### ISSUE TITLE
Component content audit [modal]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#417]

**Comment by ashleydraper** [comment]
Draft content for the [modal component](https://docs.google.com/document/d/14z_UcGPcS6JNjYgcYHNaKDnoJEZF-UawClz-F76qPIM/edit#heading=h.xv7rpjtvd3w5) is ready for review.

**Comment by ashleydraper** [comment]
@artuoma I've taken another content pass and included feedback from the team. Ready for your review.

[modal component](https://docs.google.com/document/d/14z_UcGPcS6JNjYgcYHNaKDnoJEZF-UawClz-F76qPIM/edit#heading=h.xv7rpjtvd3w5)

**Comment by extinah** [comment]
@ashleydraper  
Art and I are done with our review. There's some minor items for you to resolve before moving to development. Thanks!

**Comment by Courtney-Chittock** [comment]
I performed a final review. Just one comment. :)

**Comment by kkoryaka** [comment]
@ashleydraper this is now updated and ready for review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/components/modal.html

**Comment by ashleydraper** [comment]
Looks great! Ready to close.
