### ISSUE TITLE
Pattern content audit [profile banner]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#472]

**Comment by yesenia-gtz** [comment]
@ashleydraper @artuoma does this relate to https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/332 ? cane we close this out?

**Comment by ashleydraper** [comment]
@yesenia-gtz  Not for that reason, but yes we can close. The profile banner in prod is more like our card, unless @artuoma has more on this, I think we can close.
