### ISSUE TITLE
Create simple v6 eleventy template repository

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template#473]
Create simple one page v6 eleventy template

**Comment by kkoryaka** [comment]
@artuoma I have create repo with simple and lightweight State Web template eleventy version  https://github.com/Office-of-Digital-Services/California-State-Web-Template-eleventy

**Comment by yesenia-gtz** [comment]
@kkoryaka is this OK close out?

**Comment by yesenia-gtz** [comment]
I see no response so I am closing
