### ISSUE TITLE
Hero info design improvements

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template#480]
Review hero info patter design and suggest improvements that would go better in line with design system look and feel

Current link: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/hero-info.html

**Comment by ashleydraper** [comment]
There was a decision to merge hero info with hero banner. This pattern should be removed from development. Assigning to Konstantin to remove.

**Comment by kkoryaka** [comment]
happy to do it !

**Comment by ashleydraper** [comment]
@kkoryaka Can you share the link in staging?

**Comment by ashleydraper** [comment]
This pattern does not re-designed. We should not close until the example design has been added in dev.

**Comment by ashleydraper** [comment]
We don't have the design yet, but it will live **[here](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=109%3A5016)**.

**Comment by yesenia-gtz** [comment]
Assigning to you and @sharon-rabang pushing this to December production release milestone.

**Comment by kkoryaka** [comment]
this one was deleted from banner variation. Closing it
