### ISSUE TITLE
Apply Web Template website colors to Figma prototypes

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template#521]
Work with @kkoryaka to apply official Web Template website colors to Figma prototypes.

**Comment by sharon-rabang** [comment]
Discuss color palette studies and options in Figma to create final Figma Color Styles.
@kkoryaka Let me know when you're available to meet, thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang  here is the color scheme file with all the color variables:
https://github.com/Office-of-Digital-Services/California-State-Web-Template/blob/6.0.8/src/scss/colorscheme/colorscheme-oceanside.scss

**Comment by sharon-rabang** [comment]
10.10.22: Worked with Konstantin to determine V6 website colors.
10.11.22: Colors are ready for Sharon to apply to Figma prototypes. Sharon will let Konstantin know when their ready for Dev.

**Comment by sharon-rabang** [comment]
Figma [Website Template: Color palette](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=72%3A9374)

@kkoryaka All pages in Figma have been updated with these colors and are ready for dev. Please let me know if you have any questions or concerns.
