### ISSUE TITLE
Web Template logo refresh

### ISSUE THREAD

**Issue by sharon-rabang** [Office-of-Digital-Services/California-State-Web-Template#528]
Redesign the current logo mark to fit the V6 State Template website's look and feel. 
Consider creating a set of 3 or more logos that change upon refresh of the page. 
Examples: 
- 1 logo design that changes with different colors or patterns
- 3 modular graphic shapes from the homepage's featured banner image
- 3 bear profiles/silhouettes/paw prints or 1 of each, based on the homepage's featured banner image

**Comment by yesenia-gtz** [comment]
No need to have a logo refresh. @artuoma can we close this out?
