### ISSUE TITLE
Add drop down menu on main navigation.

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#534]
Edit the main navigation to include a drop down menu for **visual design**. Navigation menu should include:

- Template updates
- Get started 
- Structure
- Visual design (no landing page)
>> Icons
>> Color 
>> Typography
- Components
- Patterns

**Comment by kkoryaka** [comment]
@ashleydraper i have made update to navigation

**Comment by ashleydraper** [comment]
This is done. Ready to close.
