### ISSUE TITLE
Create an external link icon

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template#569]
Request JS code from design system team, or check exisiting css snippet to see if it will work for this project.

**Comment by kkoryaka** [comment]
@ashleydraper i have added the external link icon feature, please test.

**Comment by ashleydraper** [comment]
@kkoryaka I don't see it yet, should I give it a minute?

**Comment by ashleydraper** [comment]
Looks good. Ready to close.
